Adding GyuTae's SetMyEnv Script
arfc/scripts pull request #1
Opened 2019-01-03 18:34 UTC by gtw2

Adds script to setup ubuntu on a new machine

2019-02-15 20:44 UTC, katyhuff commented
The folder (and script name) setmyenv is very generic. It should refer to cyclus (envs are universal... it should be clear this is for cyclus).

2019-02-15 21:31 UTC, katyhuff requested changes

2019-02-15 21:31 UTC, katyhuff commented on setmyenv/README.md
> +Sets up original environment for Ubuntu 16.04.
I'm not sure what you mean by original? 
Maybe you mean "development" or "standalone" ?

2019-02-15 21:31 UTC, katyhuff commented on setmyenv/README.md
> +To run:
```suggestion
To run the setup script, execute: 
```

2019-02-15 21:31 UTC, katyhuff commented on setmyenv/README.md
> +`source $HOME/.bashrc`
```suggestion
`source ~/.bashrc`
```

2019-02-15 21:31 UTC, katyhuff commented on setmyenv/startup.sh
> +conda_url='https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh'
This points to a pretty specific version of anaconda doesn't it... maybe we should find the permanent URL for the newest anaconda?...  Newer anacondas appear in the archive (e.g. from december 2018) https://repo.anaconda.com/archive/

anyway I think the .io URL might not work forever (see: https://github.com/conda/conda/issues/6886) ..

2019-04-04 16:32 UTC, gwenchee commented
Perhaps add a READme about what the script does? @gtw2

2025-03-18 19:46 UTC, katyhuff commented
I think this script has been overcome by events . while it could have some value, build approaches have changed somewhat and recent attempts to install using this script no longer succeed.

2025-03-18 19:46 UTC, closed without merging